### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by DrHyperKALICH** [juribeparada/MMDVM_HS#1]
Hello!
Where can I find build and installation instructions with ADF7021?

**Comment by juribeparada** [comment]
Hi!,

most of the information is this thread in MMDVM yahoo group (you must be registered):

https://groups.yahoo.com/neo/groups/mmdvm/conversations/topics/11116?reverse=1

and there are some instructions docs in the file section in this yahoo groups.

Andy.

**Comment by juribeparada** [comment]
Added building instructions (file BUILD.txt) in the source code.
