### ISSUE TITLE
Strange signals from hotspot and Audio problem

### ISSUE THREAD

**Issue by onemikedelta** [juribeparada/MMDVM_HS#103]
My motorola dp3600 radio is missing beginning of transmissions. I realized that even 1 second transmissions are making my hotspot 3 secs of tx. I tryed to find a reason but settings looks ok. Here is my dsd+ output. That "DMR  CACH ERR slot1         BS DATA       DCC=1  Idle" lines/packets are sent at beginning of every transmission and makes my radio stuck for a few seconds. I am not sure is it mmdvm's fault or mmdvmhost or brandmeister's. Sorry if wrong page. After first few seconds everything works ok. I tried to change "EmbeddedLCOnly" option. Nothing changed. Only decreasing jitter buffer recovers audio a bit however, due to packet losses that audio is not understandable.

Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR  CACH ERR slot1         BS DATA       DCC=1  Idle
Sync:+DMR
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS DATA       DCC=1  Voice Hdr
+DMR    MS VOICE
+DMR    MS VC2
+DMR    MS VC3
+DMR    MS VC4
+DMR    MS VC5
+DMR    MS VC6
+DMR    MS VOICE
+DMR    MS VC2
+DMR    MS VC3
+DMR    MS VC4
+DMR    MS VC5
+DMR    MS VC6
+DMR    MS VOICE
+DMR    MS VC2
+DMR    MS VC3
+DMR    MS VC4    e:7r6r6r
+DMR    MS VC5    e:7m6r6r
+DMR    MS VC6    e:7r6m6r
Sync: no sync

Here is my setup:
MMDVM protocol version: 1, description: MMDVM_HS_Hat-v1.4.12 20181104 14.7456MHz ADF7021 FW by CA6JAU GitID #dec7051
and
MMDVM protocol version: 1, description: MMDVM_HS-v1.4.17 20190529 14.7456MHz ADF7021 FW by CA6JAU GitID #cc451c4
(I updated the firmware and both are same)

MMDVMHost-20181107_Pi-Star is starting
Built 09:24:10 Nov 12 2018 (GitID #9444eca)

Raspberry Pi Zero W and Pi-star image, connected to brandmeister.

I got this radio few weeks ago and didn't use much, so I don't know if it was same before but I didn't realized. TYT MD390 with md380tools firmware works perfect and gets all audio.
My final thought(completely guess) is in somewhere it tries to fill rf air data with some empty data during waiting for all packets arrived, however that "gap filler" packets are harmful for moto radio.

**Comment by juribeparada** [comment]
Unfortunately I don't have a dp3600 radio to test. I tested this fw long ago with other moto radios and it worked fine. Re-open this issue if the problem continues.
