### ISSUE TITLE
Help Selecting Correct Board For Build And Firmware

### ISSUE THREAD

**Issue by dh47** [juribeparada/MMDVM_HS#106]
Hello, I ordered the following board of bangood and need help making sure I build and compile and also get the right firmware for the following.

`https://www.banggood.com/USB-Communication-Duplex-MMDVM-Hotspot-Support-P25-DMR-YSF-2PCS-Antenna-For-Raspberry-Pi-p-1360474.html`

Which firmware should I select to flash?

Thanks.

**Comment by rogerclarkmelbourne** [comment]
The GitHub issues are for reporting bugs.

Try posting to https://forum.pistar.uk/

**Comment by dh47** [comment]
Okay.

**Comment by dh47** [comment]
Reopeing as I'm having issues signing up to that forum.  Could an admin please take a look please?  User name there is Dark_Hunter.

**Comment by phl0** [comment]
The admins of that forum are probably not reading github issues for the firmware.

**Comment by dh47** [comment]
Okay, I'll try the email.
