### ISSUE TITLE
PI-Star 4.1.2 POCSAG No start tone

### ISSUE THREAD

**Issue by citynetcomputing** [juribeparada/MMDVM_HS#125]
Hello,

Running the latest pi-star 4.1.2 (MMDVMHost-20200615_Pi-Star_v4) on STM32DVM and with POCSAG 9 out of 10 messages roughly have no start tone (preamble). once in a while i will hear it and the pager will go off. But no tone no pager..

Any ideas or fixes?

**Comment by juribeparada** [comment]
This GitHub is not the firmware for STM32DVM board
