### ISSUE TITLE
MMDVM_HS dated 20/08 Sketch to large on Arduino

### ISSUE THREAD

**Issue by bill2e0** [juribeparada/MMDVM_HS#15]
Andy
I have just downloaded the MMDVM_HS from git hub. When I try to load it to STM32 boards with Arduino, I am getting a sketch to large message. I have tried it on 2 different PC's with the same result.
Cheers
Bill
![capture](https://user-images.githubusercontent.com/31314193/29669579-dbacd860-88db-11e7-85bb-8cb6261dc106.JPG)

**Comment by phl0** [comment]
You are using an STM32F103 board obviously. AFAIK it has to be an STM32F108.

**Comment by 2e0dqd** [comment]
It should run on a STM32F103

**Comment by N4IRS** [comment]
I am wondering why your result is bigger then 64K Here is my result I got from DLing the master branch.

Sketch uses 64088 bytes (97%) of program storage space. Maximum is 65536 bytes.
Global variables use 7104 bytes of dynamic memory.

73, Steve N4IRS

**Comment by juribeparada** [comment]
Hi All, compiled with gcc under Linux or Mac the bin size is 49136 bytes. Last weekend I added some additional runtime debug messages, that uses a standard C library. Probably this is too bulky under Arduino / stm32duino. I will correct this soon. Try to compile a previous commit.

73, Andy CA6JAU.

**Comment by bill2e0** [comment]
Previous commit compiles fine, bin size around 49k bytes. Just wanted this with the quiet option behavior to mode leds. 
73, Bill  2E0FEI.

**Comment by juribeparada** [comment]
Try again, I removed the bulky function.  I will fix better later.

**Comment by bill2e0** [comment]
Thank you Andy, perfect now.
73, Bill 2E0FEI
![capture1](https://user-images.githubusercontent.com/31314193/29681895-1315a1ea-8901-11e7-8a06-2bbc047bfb79.JPG)
