### ISSUE TITLE
Can't write Firmware to Hs_Hat

### ISSUE THREAD

**Issue by dc7jzb** [juribeparada/MMDVM_HS#152]
I have a weird Problem.
I try to update the Firmware of a hs_hat by DF2ET.
I've pulled the Repo from Yesterday, changed settings of config.h to the hat.

'sudo make' works fine, without failures.
But when I start to write the Firmware to the hat, with `sudo make mmdvm_hs_hat` I get the Message that there is nothing to do for the target mmdvm_hs_hat.

Has anyone an idea what Iam doing wrong?

**Comment by phl0** [comment]
Is `stm32flash` installed and executable from `/usr/local/bin/stm32flash`?

**Comment by dc7jzb** [comment]
OK, That did it.
Now it works. Tnx.
