### ISSUE TITLE
Stlink

### ISSUE THREAD

**Issue by ea7gwc** [juribeparada/MMDVM_HS#31]
Hola.
Cuando intento grabar el STM desde la raspberry y STlink de error
Dice que no encuentra.......libstlink-shared.so.1
Veo que en utils/rpi32 esta libstlink-shared.so.1.3.1

Estoy haciendo algo mal......?

73.

**Comment by juribeparada** [comment]
Creo que ni si quiera he probado STLink desde una RPI, como es una tarea que se hace muy pocas veces (uso USB bootloader siempre), creo que solo he usado STLink desde el PC. Lo revisaré cuando pueda.

**Comment by juribeparada** [comment]
Debería estar corregido ahora
