### ISSUE TITLE
USE_ALTERNATE_POCSAG_LEDS

### ISSUE THREAD

**Issue by ea7gwc** [juribeparada/MMDVM_HS#46]
Cuando activo el uso de los LED DMR y dstar para
POCSAG, veo que deja de funcionar la indicacion
individual de DMR y Dstar.
Es un comportamiento normal ? o bug.
// Usa los LED D-Star y DMR para POCSAG
// #define USE_ALTERNATE_POCSAG_LEDS

Saludos.

**Comment by phl0** [comment]
Confirmed here. I am looking for a solution.

**Comment by phl0** [comment]
I proposed a code change with PR #48. Should be fixed if that is included in the official builds.

**Comment by phl0** [comment]
@ea7gwc Could you please pull the latest changes, re-compile and upload the firmware and test?
If all works well please close this issue.

**Comment by ea7gwc** [comment]
Ok Voy a probarlo

**Comment by ea7gwc** [comment]
Now it works ok.
Thank you.
