### ISSUE TITLE
install_fw_nanodv_usb.sh

### ISSUE THREAD

**Issue by vk7hse** [juribeparada/MMDVM_HS#66]
MMDVM_HS/scripts  the file install_fw_nanodv_usb.sh is not marked as executable

`-rw-r--r-- 1 pi-star pi-star 3001 Aug 22 10:53 install_fw_nanodv_usb.sh `

**Comment by phl0** [comment]
https://github.com/juribeparada/MMDVM_HS/pull/67

**Comment by juribeparada** [comment]
Merged #67, thank you Flo
