### ISSUE TITLE
Pinout to users RPi

### ISSUE THREAD

**Issue by KC5CQW** [juribeparada/MMDVM_HS#7]
Please include a pinout document (or append to the readme) to describe the connections between the ZUM HS board and the RPi. This information has proven to be difficult to find and open to interpretation. From skimming the code with an uneducated eye, It looks like the USB port is the only connection. Serial, I2C and AVR ports... (Are they only for direct access for debugging and/or use with LCD's and FW updates?)

**Comment by juribeparada** [comment]
General pinout is described in BUILD.txt at the end. Regarding serial port for RPi, it is also in that document:
- Serial ports:
TXD            PA9 (serial port host communication)
RXD            PA10 (serial port host communication)
...
Please see the document and if you have any suggestions please tell me. Also you can submit a PR to improve the documentation if you like.

Regards, Andy.
