### ISSUE TITLE
MMDVM Dual (V1.2) Issue on update

### ISSUE THREAD

**Issue by TheOriginalFreddoFrog** [juribeparada/MMDVM_HS#72]
Andy (and Roger),

I am receiving this on a firmware upgrade on a standard "Chinese" MMDVM Dual 1.2 (on 2 arduino bases):

_http://github.com/rogerclarkmelbourne/arduino_stm32

Using Parser : Raw BINARY
Interface serial_posix: 57600 8E1
Failed to init device._

I have used **sudo pistar-mmdvmhshatflash hs_dual_hat** : HS_DUAL_HAT (14.7456MHz TCXO) and the manual script **install_fw_hsdualhat.sh** - both with the same outcome.

Yes the board has a 14.7456MHz TCXO.

A Version 1.0 board here (without the USB connector) upgrades perfectly. Things do not make sense !

Any suggestions???

73.

Steve I
VK3VM / VK3SIR

**Comment by TheOriginalFreddoFrog** [comment]
Roger,

Good call. I went over the STM with an iron … thwere saoldwer that the manufacturer was using was appaling and it took quite some time to "clean up" and ensure that the poor chip was properly soldered in....

And yes, I say poor chip....

It has now updated.

73 and thanks for the tip !!!

Steve I
VK3VM / VK3SIR

**Comment by rogerclarkmelbourne** [comment]
Glad that fixed it. Poor soldering is a problem that is reported a lot on various forums including the one I run www.stm32duino.com
