### ISSUE TITLE
D-STAR Connection Issues

### ISSUE THREAD

**Issue by mrickey** [juribeparada/MMDVM_HS#9]
I have a ZUMspot and am having an issue with D-STAR.

I've noticed the ZUMspot will scan through the modes two or three times before locking into D-STAR. I do not experience this with DMR and Fusion.

Here is a video that demonstrates what I'm seeing. https://youtu.be/Ht4lTHcTGSA

Any ideas? Is this a configuration issue, or something with how the scanning is done?

Thanks in advance for your help.

**Comment by juribeparada** [comment]
Hi, it is not a configuration issue, it is how the scanning mode works. I know, d-star detection is slow, probably will be fix in the future.

Regards,
Andy.
